---
name: umfive
channels:
  - conda-forge
  - nodefaults  # stay away from Anaconda like the plague

dependencies:
  # core dependencies
  - python >=3.11
  - numpy >=2.0.0
  - pyfive >=1.1.1
  - cftime
  # testing and linting
  - pre-commit  # with ruff and mypy
  - pytest
  - pytest-cov
  - pytest-html
  - pytest-xdist
  - fsspec
  # documentation dependencies
  - autodocsumm
  - sphinx
  - furo
  - pip